### ISSUE TITLE
[Bug] Ticker error

### ISSUE THREAD

**Issue by marchellodev** [marchellodev/sharik#85]
Steps to reproduce:
1. Share any file or text
2. Clean history

Error:

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
_MaterialState#51bb6(tickers: tracking 1 ticker) was disposed with an active Ticker.

_MaterialState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

The offending ticker was: _WidgetTicker(created by _MaterialState#51bb6(tickers: tracking 3 tickers))
The stack trace when the _WidgetTicker was actually created was:
#0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:67:40)
#1      new Ticker (package:flutter/src/scheduler/ticker.dart:69:6)
#2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:271:81)
#3      TickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:202:34)
#4      new AnimationController (package:flutter/src/animation/animation_controller.dart:247:21)
#5      new MaterialInkSplash (package:sharik/utils/material_ink_well.dart:157:30)
#6      MaterialInkSplashFactory.create (package:sharik/utils/material_ink_well.dart:64:12)
#7      _InkResponseState._createInkFeature (package:flutter/src/material/ink_well.dart:900:72)
#8      _InkResponseState._startSplash (package:flutter/src/material/ink_well.dart:974:42)
#9      _InkResponseState._handleTapDown (package:flutter/src/material/ink_well.dart:959:5)
#10     TapGestureRecognizer.handleTapDown.<anonymous closure> (package:flutter/src/gestures/tap.dart:580:61)
#11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#12     TapGestureRecognizer.handleTapDown (package:flutter/src/gestures/tap.dart:580:11)
#13     BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:287:5)
#14     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:265:7)
#15     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443:20)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
#19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#26     _invoke1 (dart:ui/hooks.dart:182:10)
#27     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
#28     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
(elided 3 frames from dart:async)

When the exception was thrown, this was the stack: 
#0      TickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:219:13)
#1      TickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:237:6)
#2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4800:11)
#3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1847:13)
#4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
...
====================================================================================================
```

**Comment by marchellodev** [comment]
The issue still persists, even though it is not critical
